1004 OAuth2 client credentials flow
ethyca/fidesops pull request #1159
Opened 2022-08-25 19:57 UTC by galvana

# Purpose
Adding the client credential OAuth2 flow. We previously only supported the authentication code flow but we need to be able to support additional flows for different SaaS connectors.

# Changes
- Renamed the existing `oauth2` strategy to `oauth2_authentication_code` and added `oauth2_client_credentials`
- Moved shared OAuth2 functionality to a base class which is extended for each OAuth2 flow
- Added unit tests for Client Credentials flow
- Updated documentation to include the new flow

# Checklist
- [ ] Update [`CHANGELOG.md`](https://github.com/ethyca/fidesops/blob/main/CHANGELOG.md) file
  - [ ] Merge in main so the most recent `CHANGELOG.md` file is being appended to
  - [ ] Add description within the `Unreleased` section in an appropriate category. Add a new category from the list at the top of the file if the needed one isn't already there.
  - [ ] Add a link to this PR at the end of the description with the PR number as the text. example: [#1](https://github.com/ethyca/fidesops/pull/1)
- [ ] Applicable documentation updated (guides, quickstart, postman collections, tutorial, fidesdemo, [database diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/development/update_erd_diagram.md).
- If docs updated (select one):
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
- [ ] Good unit test/integration test coverage
- [ ] This PR contains a DB migration. If checked, the reviewer should confirm with the author that the [down_revision correctly references the previous migration](https://ethyca.github.io/fidesops/development/contributing_details/#alembic-migrations) before merging
- [ ] The `Run Unsafe PR Checks` label has been applied, and checks have passed, if this PR touches any external services

# Ticket

Fixes #1004

2022-08-25 19:59 UTC, galvana commented on src/fidesops/ops/api/v1/endpoints/oauth_endpoints.py
> +        connection_config.secrets = {**connection_config.secrets, "code": code}  # type: ignore
Adding the code outside of the `get_access_token` to make the function reusable between the different OAuth2 flows.

2022-08-25 20:04 UTC, galvana commented on src/fidesops/ops/service/authentication/authentication_strategy_oauth2_base.py
> +        expires_in = self.expires_in or response.get("expires_in")
Switching order to be able to override expiration even if one is provided in the token response.

2022-08-26 15:20 UTC, adamsachs commented on src/fidesops/ops/api/v1/endpoints/saas_config_endpoints.py
> +        auth_strategy: OAuth2AuthorizationCodeAuthenticationStrategy = get_strategy(
i smell a merge conflict with https://github.com/ethyca/fidesops/pull/1163 😅

2022-08-26 18:55 UTC, adamsachs approved these changes
this looks really good to me - nice job abstracting out the common components. i have only some very minor comments - please let me know what you think, but i don't consider them blocking.

also, just noting that we'll need to resolve merge conflicts in https://github.com/ethyca/fidesops/pull/1163 once this is merged.

2022-08-26 18:55 UTC, adamsachs commented on tests/ops/service/authentication/test_authentication_strategy_oauth2_client_credentials.py
> +        # cast some time magic
who said time travel wasn't possible

2022-08-26 18:55 UTC, adamsachs commented on tests/ops/service/authentication/test_authentication_strategy_oauth2_client_credentials.py
> +    # make sure we can use the expires_in value in the config if no expires_in is provided
nit: should this comment be moved to the docstring for the test method?

2022-08-26 19:02 UTC, adamsachs requested changes
sorry, i spoke a bit too soon on my previous review -- i shouldn't have approved yet because you're missing a `CHANGELOG.md` update. i actually think this change should be logged as under `Breaking Changes` because technically it would break any existing configs that have the old `oauth2` auth strategy name.

2022-08-26 20:11 UTC, galvana commented on src/fidesops/ops/service/authentication/authentication_strategy_oauth2_base.py
> +    @abstractmethod
Nice catch, I deleted the re-definition

2022-08-26 20:19 UTC, galvana commented
Updated the changelog with the breaking change and made the requested changes.

2022-08-29 13:09 UTC, adamsachs approved these changes
all looks good to me, thanks for addressing the minor comments!

2022-08-29 16:40 UTC, merged