updates docs for supported masking strategies and associated configs
ethyca/fidesops pull request #173
Opened 2022-01-25 18:20 UTC by eastandwestwind

# Purpose
Update docs to reflect current supported masking strategies

# Changes
- Adds to `masking_strategies.md`. Screenshot of page for ease of review:
![screencapture-0-0-0-0-8000-fidesops-guides-masking-strategies-2022-01-25-12_17_43](https://user-images.githubusercontent.com/7697292/151035732-03bb8895-3888-4a81-8514-eef83bd11656.png)

# Checklist

- [ ] Applicable documentation updated (guides, quickstart, postman collections, tutorial, fidesdemo, [database diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/development/update_erd_diagram.md)
- [ ] Good unit test/integration test coverage

# Ticket

Fixes #155

2022-01-26 20:25 UTC, seanpreston commented on docs/fidesops/docs/guides/masking_strategies.md
> +Erasure requests will replace mask data with the chosen masking strategy.
I think we meant to remove either `mask` or `replace` in this line?

2022-01-26 20:28 UTC, seanpreston commented on docs/fidesops/docs/guides/masking_strategies.md
> +Masks the input value by returning a hashed version of the input value. Is deterministic such that the same input value will mask to the same value within the same privacy request. This is not the ca
Consider:
```
Masks the data by hashing the input before returning it. The hash is deterministic such that the same input will return the same output within the context of the same privacy request. This is not the case when the masking service is called as a standalone service, outside the context of a privacy request.
```

2022-01-26 20:29 UTC, seanpreston commented on docs/fidesops/docs/guides/masking_strategies.md
> +Masks by encrypting the value using AES. Is deterministic such that the same input value will mask to the same value within the same privacy request. This is not the case when the masking service is
As above for deterministic explanation

2022-01-26 20:29 UTC, seanpreston commented on docs/fidesops/docs/guides/masking_strategies.md
> +Masks the input value by using the HMAC algorithm along with a hashed version of the data and a secret key. Is deterministic such that the same input value will mask to the same value within the same
As above for deterministic explanation

2022-01-26 20:30 UTC, seanpreston requested changes
A few small language tweaks but a very useful addition nonetheless, thanks @eastandwestwind

2022-01-26 21:46 UTC, eastandwestwind commented
@seanpreston thanks for the comments! I've made those updates

2022-01-26 22:15 UTC, pattisdr approved these changes
great updates @eastandwestwind 🏆

2022-01-27 15:54 UTC, seanpreston approved these changes

2022-01-27 15:54 UTC, merged