220 Documentation for setting up debugging in Jet Brains IDE.
ethyca/fidesops pull request #225
Opened 2022-02-17 15:42 UTC by nschoenbrot

# Purpose
Documentation for debugging with a Jet Brains IDE. 

# Changes
Adds a md file and screenshots. 

# Ticket
220

2022-02-22 14:16 UTC, seanpreston requested changes
Awesome start! We need a bit more prose contextualising each step, especially in `Connect to Docker daemon` and `Configure Python Remote Interpreter`.

2022-03-02 17:27 UTC, nschoenbrot commented
> Awesome start! We need a bit more prose contextualising each step, especially in `Connect to Docker daemon` and `Configure Python Remote Interpreter`.

Pushed up a commit with more details added to the instructions.

2022-03-02 17:32 UTC, seanpreston commented on docs/fidesops/docs/development/jetbrains_debugging.md
> +See screenshot bellow:
Typo: below

2022-03-02 17:35 UTC, seanpreston commented
Thanks @nschoenbrot, just that one typo then it's good to merge

2022-03-02 18:36 UTC, nschoenbrot commented on docs/fidesops/docs/development/jetbrains_debugging.md
> +See screenshot bellow:
Thanks, I pushed up the fix.

2022-03-02 20:15 UTC, nschoenbrot commented
> Thanks @nschoenbrot, just that one typo then it's good to merge

Thanks, I made the fix.

2022-03-03 22:40 UTC, seanpreston approved these changes

2022-03-03 22:40 UTC, merged