[Misc. DevOps] Fix data seeding for MariaDB
ethyca/fidesops pull request #230
Opened 2022-02-23 02:10 UTC by seanpreston

# Purpose

# Changes

-
# Checklist

- [ ] Applicable documentation updated (guides, quickstart, postman collections, tutorial, fidesdemo, [database diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/development/update_erd_diagram.md))
- [ ] Good unit test/integration test coverage
- [ ] This PR contains a DB migration. If checked, the reviewer should confirm with the author that the [down_revision correctly references the previous migration](https://ethyca.github.io/fidesops/development/contributing_details/#alembic-migrations) before merging
- [ ] The `Run Unsafe PR Checks` label has been applied, and checks have passed, if this PR touches any external services

2022-03-02 18:01 UTC, pattisdr requested changes
Thanks for your work to seed the database so we can use it in local testing!  Just a few requested changes -

2022-03-03 17:56 UTC, seanpreston commented on tests/integration_tests/setup_scripts/mariadb_setup.py
> +    with open("./data/sql/mariadb_example_data.sql", "r") as query_file:
Great spot, thanks!

2022-03-03 18:38 UTC, pattisdr commented on tests/fixtures/mariadb_fixtures.py
> +        ]
thanks for reticketing!

2022-03-03 18:55 UTC, pattisdr approved these changes
looks great thanks 🏆

2022-03-03 18:55 UTC, merged