507- adds DRP GET data rights endpoint
ethyca/fidesops pull request #526
Opened 2022-05-18 02:07 UTC by eastandwestwind

# Purpose
Adds DRP Get data rights endpoint

# Changes
- Adds GET data rights endpoint
- Adds appropriate tests
- Updates postman collection

# Checklist
- [ ] Update [`CHANGELOG.md`](https://github.com/ethyca/fidesops/blob/main/CHANGELOG.md) file in appropriate sections
- [ ] Applicable documentation updated (guides, quickstart, postman collections, tutorial, fidesdemo, [database diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/development/update_erd_diagram.md).
- If docs updated (select one):
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
- [ ] Good unit test/integration test coverage
- [ ] This PR contains a DB migration. If checked, the reviewer should confirm with the author that the [down_revision correctly references the previous migration](https://ethyca.github.io/fidesops/development/contributing_details/#alembic-migrations) before merging
- [ ] The `Run Unsafe PR Checks` label has been applied, and checks have passed, if this PR touches any external services

# Ticket

Fixes #507

2022-05-20 14:15 UTC, conceptualshark requested changes
looks good otherwise from a docs standpoint 👍

2022-05-20 14:15 UTC, conceptualshark commented on docs/fidesops/docs/guides/data_rights_protocol.md
> +```json title="<code>GET /api/v1/drp/data-rights}</code>"
```suggestion
```json title="<code>GET /api/v1/drp/data-rights</code>"
```
just this dangling curly brace

2022-05-24 19:54 UTC, seanpreston commented on tests/api/v1/endpoints/test_drp_endpoints.py
> +        return V1_URL_PREFIX + DRP_DATA_RIGHTS
I'm not sure I see a good way around this in the near-term — this may be confusing because our API is versioned differently to the DRP version.

2022-05-24 19:56 UTC, seanpreston commented on tests/api/v1/endpoints/test_drp_endpoints.py
> +            "actions": ["access", "deletion"],
Could you test against the enums here? That way if this changes in subsequent versions of DRP we won't need to update the tests.

2022-05-24 20:24 UTC, seanpreston requested changes
Thanks @eastandwestwind — a few minor changes and some conflicts to fix!

2022-05-25 17:21 UTC, seanpreston approved these changes

2022-05-25 17:22 UTC, merged